import type { AIVideoProvider, VideoGenerationResult } from "../types";
import { ProviderCallError } from "../types";

// No first-party video-rendering API is wired up. This is the architecture
// a real provider (Runway, Pika, Google Veo, Sora API, etc.) plugs into —
// implement AIVideoProvider and register it in ../index.ts. Until then this
// intentionally fails rather than faking a successful render, per product
// requirement: "Do NOT fake successful video generation."

export class UnconfiguredVideoProvider implements AIVideoProvider {
  readonly id = "unconfigured";

  async generateVideo(): Promise<VideoGenerationResult> {
    throw new ProviderCallError(
      this.id,
      new Error(
        "No video rendering provider is connected yet. The video PLAN (hook/scenes/CTA/caption) is generated by the text model above and saved — actual video rendering requires connecting a provider such as Runway, Pika, or Google Veo. Set AI_VIDEO_PROVIDER and its API key, then implement AIVideoProvider in lib/ai/providers/video.ts."
      )
    );
  }
}
